//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cust
    {
        public int ID { get; set; }
        public string Cust_name { get; set; }
        public string Cust_email { get; set; }
        public string Cust_phine { get; set; }
    }
}
