//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pur
    {
        public int ID { get; set; }
        public Nullable<int> Cat_id { get; set; }
        public Nullable<int> Supp_id { get; set; }
        public string Pur_name { get; set; }
        public string Pur_type { get; set; }
        public string Pur_cat { get; set; }
        public string Pur_supp { get; set; }
        public string Pur_det { get; set; }
        public Nullable<double> Pur_buy { get; set; }
        public Nullable<double> Pur_sell { get; set; }
        public Nullable<double> Pur_qt { get; set; }
        public Nullable<double> Pur_tbuy { get; set; }
        public Nullable<double> Pur_tsell { get; set; }
        public Nullable<double> Pur_trevn { get; set; }
    
        public virtual TB_cat TB_cat { get; set; }
        public virtual TB_Supp TB_Supp { get; set; }
    }
}
