//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sell
    {
        public int ID { get; set; }
        public string Sell_namme { get; set; }
        public string Sell_cust { get; set; }
        public Nullable<double> Sell_price { get; set; }
        public Nullable<double> Sell_qt { get; set; }
        public Nullable<double> Sell_tprice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
