//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Users
    {
        public int ID { get; set; }
        public string User_name { get; set; }
        public string User_pass { get; set; }
        public string User_role { get; set; }
        public string User_state { get; set; }
    }
}
